// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://istzgvbzydhlxvvqdnyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlzdHpndmJ6eWRobHh2dnFkbnlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MzYwNTEsImV4cCI6MjA1OTAxMjA1MX0.tF5PnJqOR_4b8Rgl0ablN-7paX8PhIUSKHyq9wUbouQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);